version: '3.9'

services:
  mongodb-service:
    container_name: com.techbow.notification.mongodb
    image: mongo
    ports:
      - 8083:27017
    volumes:
      - "mongodb-volume:/data/db"

  redis-service:
    container_name: com.techbow.notification.redis
    image: redis
    ports:
      - 8084:6379

  mysql-service:
    container_name: com.techbow.notification.mysql
    image: mysql
    ports:
      - 8087:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "root-password"
      MYSQL_DATABASE: "default_db"
    volumes:
      - "mysql-volume:/var/lib/mysql"

  rabbitmq-service:
    container_name: com.techbow.notification.rabbitmq
    image: 'library/rabbitmq:3-management'
    ports:
      - 8085:5672
      - 8086:15672

  zipkin-service:
    container_name: com.techbow.notification.zipkin
    image: openzipkin/zipkin
    ports:
      - 8090:8090
      - 8091:9411

  prometheus-services:
    container_name: com.techbow.notification.prometheus
    image: prom/prometheus
    ports:
      - 8092:9090
    volumes:
      - ${HOME}/techbow/gs-notification-service/initial/notification-service-configs/prometheus-service.yml:/etc/prometheus/prometheus.yml

  grafana-services:
    container_name: com.techbow.notification.grafana
    image: grafana/grafana
    ports:
      - 8093:3000
    volumes:
      - ${HOME}/techbow/gs-notification-service/initial/notification-service-configs/grafana-service.ini:/etc/grafana/grafana.ini

volumes:
  mongodb-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/mapped-volumes/mongodb-volume
  mysql-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/mapped-volumes/mysql-volume
